[package]
name = "dexios"
version = "8.2.0"
authors = ["brxken128 <brxken128@tutanota.com>"]
readme = "README.md"
edition = "2021"
description = "Secure, fast and authenticated command-line encryption of files with modern algorithms and an audited encryption backend."
keywords = ["encryption", "utility", "file", "command-line", "secure"]
categories = ["cryptography", "command-line-utilities"]
rust-version = "1.57"
repository = "https://github.com/brxken128/dexios"
homepage = "https://github.com/brxken128/dexios"
documentation = "https://brxken128.github.io/dexios"
license = "BSD-2-Clause"

# this is for sites other than crates.io, who may still use it
[badges]
maintenance = { status = "actively-developed" }

[dependencies]
aes-gcm = "0.9.4"
chacha20poly1305 = "0.9.0"
deoxys = "0.0.2"
zeroize = "1.3.0"
argon2 = "0.4.0"
blake3 = "1.3.1"
aead = { version = "0.4.3", features = ["stream"] }
hmac = "0.12.1"
sha2 = "0.10.2"
rand = "0.8.5"

clap = { version = "3.1.18", features = ["cargo"] }
anyhow = "1.0.57"
paris = { version = "1.5.13", features = ["macros"] }
termion = "1.5.6"

zip = { version = "0.6.2", default-features = false }
