[package]
name = "dexios"
version = "6.3.2"
edition = "2021"
description = "Secure command-line encryption of files."
repository = "https://github.com/brxken128/dexios"
license = "BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = { version = "0.9.4", features = ["stream"] }
clap = "3.1.18"
anyhow = "1.0.57"
rand = "0.8.5"
rpassword = "6.0.1"
argon2 = "0.4.0"
blake3 = "1.3.1"