[package]
name = "dexios"
version = "1.9.2"
edition = "2021"
description = "Secure command-line encryption of files."
repository = "https://github.com/brxken128/dexios"
license = "BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.9.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
clap = "3.1.12"
base64 = "0.13.0"
anyhow = "1.0.57"
ring = "0.16.20"
rand = "0.8.5"
rpassword = "6.0.1"
sha3 = "0.10.1"