[workspace]

members = [
    "dexios",
    "dexios-core",
]

[patch.crates-io]
# we should update core version to use features correctly
dexios-core = { git = "https://github.com/brxken128/dexios", branch = "master" }
