[package]
name = "dexios"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.9.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
clap = "3.1.12"
base64 = "0.13.0"
anyhow = "1.0.57"
colored = "2.0.0"
ring = "0.16.20"
rand = "0.8.5"
rpassword = "6.0.1"