[package]
name = "dexios"
version = "7.2.7"
authors = ["brxken128"]
readme = "README.md"
edition = "2021"
description = "Secure command-line encryption of files."
keywords = ["encryption", "utility", "file", "command-line", "secure"]
categories = ["cryptography", "command-line-utilities"]
rust-version = "1.57"
repository = "https://github.com/brxken128/dexios"
license = "BSD-2-Clause"

[dependencies]
aes-gcm = { version = "0.9.4", features = ["stream"] }
clap = { version = "3.1.18", features = ["cargo"] }
anyhow = "1.0.57"
rand = "0.8.5"
rpassword = "6.0.1"
argon2 = "0.4.0"
blake3 = "1.3.1"
secrecy = "0.8.0"