[package]
name = "dexios-core"
description = "The core library behind Dexios. It contains the cryptographic functions and it manages encrypted file headers."
version = "0.0.0"
edition = "2021"
license = "BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
aes-gcm = "0.9.4"
chacha20poly1305 = "0.9.0"
deoxys = "0.0.2"
zeroize = "1.3.0"
argon2 = "0.4.0"
aead = { version = "0.4.3", features = ["stream"] }
rand = "0.8.5"