name: Build and Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Audit
      uses: actions-rs/cargo@v1
      with:
        command: audit

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --no-deps

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --release

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Strip
      run: strip target/release/dexios
    - name: Upload Binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dexios
        path: target/release/dexios