name: Build and Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Audit
      uses: actions-rs/cargo@v1
      with:
        command: audit

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --no-deps

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --release

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      env:
        RUSTFLAGS: -Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3
      with:
        command: build
        args: --release
    - name: Strip
      run: strip target/release/dexios
    - name: Hash the Binary
      run: sha256sum target/release/dexios
    - name: Upload Binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dexios-linux-amd64
        path: target/release/dexios
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      env:
        RUSTFLAGS: -Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3
      with:
        command: build
        args: --release
    - name: Upload Binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dexios-windows-amd64
        path: target/release/dexios.exe