name: Build and Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - name: Audit
      run: cargo audit
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - name: Clippy
      run: cargo clippy --no-deps
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - name: Check
      run: cargo check --release
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - name: Build
      run: cargo build --release
    - name: Strip
      run: strip target/release/dexios
    - name: Upload binrary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dexios
        path: target/release/dexios