name: Dexios Tests

on:
  workflow_dispatch:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Strip
      run: strip target/release/dexios
    - name: Upload Binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dexios
        path: target/release/dexios
        retention-days: 1
  memory-mode:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Retrieve Dexios
      uses: actions/download-artifact@v3
      with:
        name: dexios
        path: target/release/dexios
    - name: Copy the Binary
      run: cp target/release/dexios .
    - name: Generate test file
      run: dd if=/dev/urandom of=100MB.bin bs=1M count=100
    - name: Generate keyfile
      run: dd if=/dev/urandom of=keyfile bs=1 count=4096
    - name: Encrypt in hash mode
      run: dexios -emHyk keyfile 100MB.bin 100MB.enc 
    - name: Decrypt in hash mode
      run: dexios -dmHyk keyfile 100MB.enc 100MB.bin
  stream-mode:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Retrieve Dexios
      uses: actions/download-artifact@v3
      with:
        name: dexios
        path: target/release/dexios
    - name: Copy the Binary
      run: cp target/release/dexios .
    - name: Generate test file
      run: dd if=/dev/urandom of=100MB.bin bs=1M count=100
    - name: Generate keyfile
      run: dd if=/dev/urandom of=keyfile bs=1 count=4096
    - name: Encrypt in stream mode
      run: dexios -esHyk keyfile 100MB.bin 100MB.enc
    - name: Decrypt in stream mode
      run: dexios -dsHyk keyfile 100MB.enc 100MB.bin
  erase:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Retrieve Dexios
      uses: actions/download-artifact@v3
      with:
        name: dexios
        path: target/release/dexios
    - name: Copy the Binary
      run: cp target/release/dexios .
    - name: Generate test file
      run: dd if=/dev/urandom of=100MB.bin bs=1M count=100
    - name: Generate keyfile
      run: dd if=/dev/urandom of=keyfile bs=1 count=4096
    - name: Encrypt and erase afterwards
      run: dexios -eHy --erase -k keyfile 100MB.bin 100MB.enc
    - name: Decrypt and erase afterwards
      run: dexios -dHy --erase -k keyfile 100MB.enc 100MB.bin
  large-file:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Retrieve Dexios
      uses: actions/download-artifact@v3
      with:
        name: dexios
        path: target/release/dexios
    - name: Copy the Binary
      run: cp target/release/dexios .
    - name: Generate test file
      run: dd if=/dev/urandom of=1GB.bin bs=1M count=1000
    - name: Generate keyfile
      run: dd if=/dev/urandom of=keyfile bs=1 count=4096
    - name: Encrypt 1GB file
      run: dexios -eHyk keyfile 1GB.bin 1GB.enc
    - name: Decrypt 1GB file
      run: dexios -dHyk keyfile 1GB.enc 1GB.bin
  small-file:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve Dexios
      uses: actions/download-artifact@v3
      with:
        name: dexios
        path: target/release/dexios
    - name: Copy the Binary
      run: cp target/release/dexios .
    - name: Generate test file
      run: dd if=/dev/urandom of=1KB.bin bs=1 count=1024
    - name: Generate keyfile
      run: dd if=/dev/urandom of=keyfile bs=1 count=4096
    - name: Encrypt 1KB file
      run: dexios -eHyk keyfile 1KB.bin 1KB.enc
    - name: Decrypt 1KB file
      run: dexios -dHyk keyfile 1KB.enc 1KB.bin